EVAL:
  PATH:
    SEG: "/data/test/label/"
    GT: "/data/test/gt/"
    RESULT: "./eval.csv"
  METRICS: [
      "IOU",
      "Dice",
      "TP",
      "TN",
      "Precision",
      "Recall",
      "Sensitivity",
      "Specificity",
      "Accuracy",
      "Kappa",
      "Dice",
      "IOU",
      "Assd",
      "Ravd",
    ]
